image: node:21-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
  script:
    - npm ci
    - npm run build --prod

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
    - apk add --no-cache openssh-client
  script:
      - pwd
    - pwd
    - pwd
    - npm ci
    - npm run build --prod
    - ls -la dist
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -o StrictHostKeyChecking=no -r dist/front-end $$USER@$$IP_ADDRESS:/tmp/angular-dist/
    - ssh $USER@$IP_ADDRESS "bash /home/ubuntu/deployments/deploy.sh"
  artifacts:
    paths:
      - dist/front-end
  only:
    - main  
