image: node:21-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build --prod

deploy:
  stage: deploy
  script:
    - scp -o StrictHostKeyChecking=no -r dist/mux-ui /tmp/angular-dist/  
  artifacts:
    paths:
      - dist/mux-ui  
  only:
    - main  
