image: node:lts-alpine AS builder

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build --prod

deploy:
  stage: deploy
  script:
    - scp -o StrictHostKeyChecking=no -r dist/your-angular-app-name /tmp/angular-dist/  # Replace with your project name
  artifacts:
    paths:
      - dist/your-angular-app-name/  # Replace with your project name
  only:
    - master  # Run on pushes to master branch
