image: node:21-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
  script:
    - npm ci
    - npm run build --prod

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
    - apk add --no-cache openssh-client
  script:
    - scp -o StrictHostKeyChecking=no -r dist/mux-ui /tmp/angular-dist/
    - bash /home/ubuntu/deployments/deploy.sh  
  artifacts:
    paths:
      - dist/mux-ui  
  only:
    - main  
